<a href="https://colab.research.google.com/github/Ramandeep-Singh17/Movona/blob/main/MovieRecommendations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('/content/movies_metadata.csv')
df.head()

/tmp/ipykernel_376/3569830623.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('/content/movies_metadata.csv')

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [ ]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [ ]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [ ]:
df.shape

(45466, 24)

In [ ]:
df.isnull().sum()
#kitne null values hai check karenge

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(13)

In [ ]:
df= df.drop_duplicates().reset_index(drop=True)

In [ ]:
#sare duplicte ko remove kar diye
df.duplicated().sum()

np.int64(0)

In [ ]:
df = df[['title', 'overview', 'genres','tagline','vote_average','popularity']]

In [ ]:
df

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",NaN,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",Just When His World Is Back To Normal... He's ...,5.7,8.387519
...,...,...,...,...,...,...
45448,Subdue,Rising and falling between a man and woman.,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",Rising and falling between a man and woman,4.0,0.072051
45449,Century of Birthing,An artist struggles to finish his work while a...,"[{'id': 18, 'name': 'Drama'}]",NaN,9.0,0.178241
45450,Betrayal,"When one of her hits goes wrong, a professiona...","[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",A deadly game of wits.,3.8,0.903007
45451,Satan Triumphant,"In a small town live two brothers, one a minis...",[],NaN,0.0,0.003503
45452,Queerama,50 years after decriminalisation of homosexual...,[],NaN,0.0,0.163015

In [ ]:
df.isnull().sum()

title               6
overview          954
genres              0
tagline         25045
vote_average        6
popularity          5
dtype: int64

In [ ]:
#hm overviw tagline genre ko sath me jod denge taki hm is sabke text ko number me ek stah convert kar dnege

### 🧹 Handling Missing Titles

`title` column me agar missing values hain to unhe remove karna zaroori hai.  
Kyuki title movie ki unique identity hoti hai, ise randomly fill nahi kiya ja sakta.  
Isliye hum missing `title` wali rows ko drop karenge taaki recommendation system me ambiguity na aaye.

In [ ]:
df = df.dropna(subset=['title'])

### 📝 Handling Missing Overview

`overview` movie ka description hota hai, lekin agar kisi movie ka overview available nahi hai to hum usme kuch assume ya random text nahi likh sakte.  
Isliye missing `overview` values ko hum empty string (`""`) se fill kar rahe hain.  
Isse vectorization process break nahi hoga aur galat information bhi add nahi hogi.

In [ ]:
df['overview'] = df['overview'].fillna('')

In [ ]:
df.iloc[0]['genres']
#isme animation genre hai jo name ke nadar hai

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

### ⚡ Lambda Function (Short Explanation)

- `lambda` ek chhota anonymous function hota hai (without name).
- Iska use tab karte hain jab simple logic inline likhna ho.
- Yaha `apply()` ke saath use kiya gaya hai taaki har row ke `genres` ko process kar sake.
- Ye har value par operation karke cleaned genre names return karta hai.

In [ ]:
import ast
df['genres'] = df['genres'].apply(lambda x :" ".join([i['name'] for i in ast.literal_eval(x)]))

### 📦 `import ast` kya hota hai?

`ast` (Abstract Syntax Tree) Python ka built-in module hai.  
Hum isse `ast.literal_eval()` use karte hain taaki string ko safely Python object (list, dict, etc.) me convert kar sakein.  

Yaha `genres` string format me tha (list of dictionaries jaisa),  
isliye `literal_eval()` se use actual list me convert kiya gaya.

In [ ]:
df.head()

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,NaN,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519

In [ ]:
df['tagline'] = df['tagline'].fillna('')

In [ ]:
df.isnull().sum()
#pahle vote avg and popularity  me tha wo ab hat gya beacuse wo tile se hi related tha

title           0
overview        0
genres          0
tagline         0
vote_average    0
popularity      0
tags            0
dtype: int64

In [ ]:
df['tags'] = df['overview']+ " " + df['genres'] +" "+ df['tagline']

### 🎬 Feature Combination for Content-Based Recommendation

Hum `overview`, `genres`, aur `tagline` ko combine kar rahe hain taaki movie ka complete textual description ek jagah mil sake.  
Is combined text ko hum numerical vectors (TF-IDF / CountVectorizer) me convert karenge.  
Isse har movie ek vector ban jaati hai, jise hum cosine similarity se compare karke similar movies recommend kar sakte hain.

In [ ]:
df.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,Just when George Banks has recovered from his ...

In [ ]:
df['tags'][1]
#tags combination hai overivew genre tagline ka

"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. Adventure Fantasy Family Roll the dice and unleash the excitement!"

### 🔎 NLP Preprocessing (What & Why)

Hum movie text data ko clean aur normalize kar rahe hain taaki model ko sirf meaningful words mile.  
Is process me lowercase conversion, punctuation removal, stopwords removal aur lemmatization kiya ja raha hai.  
Isse noise kam hota hai aur similarity calculation zyada accurate ho jaati hai.

In [ ]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

`re` Python ka Regular Expression library hai jo text me pattern match aur unwanted characters remove karne ke liye use hota hai.

In [ ]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [ ]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [ ]:
stop_words.discard('not')

In [ ]:
#text preprocessing
def preprocess_text(text):
  #lowercase
  text = str(text).lower()
  #removed the punctuations
  text = re.sub(r'[^a-zA-Z\s]', '', text)

  words = text.split()
  #remove stopwords
  words = [word for word in words if word not in stop_words]

  #lemmatize
  words = [lemmatizer.lemmatize(word) for word in words]

  return " ".join(words)

In [ ]:

df['tags'] = df['tags'].apply(preprocess_text)

In [ ]:
df['tags'][1]

'sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult who trapped inside game year living room alans hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creature adventure fantasy family roll dice unleash excitement'

In [ ]:
df = df.reset_index(drop = True)
#index reset jo drop kiye the duplicate unka khali jagah gayab hoke sab line se hoga

In [ ]:

indices = pd.Series(df.index,index = df['title']).drop_duplicates()#deop duplicate yaha necessary nhi hai
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45442
Century of Birthing            45443
Betrayal                       45444
Satan Triumphant               45445
Queerama                       45446
Length: 45447, dtype: int64

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

### TF-IDF

TF-IDF text ko numerical vectors me convert karta hai jahan important (rare) words ko zyada weight milta hai aur common words ko kam.  
Isse cosine similarity se better movie recommendations milti hain.

In [ ]:
tfidf = TfidfVectorizer(max_features=50000,ngram_range=(1,2),stop_words='english')

### TF-IDF Vectorizer Setup

Hum `TfidfVectorizer` use kar rahe hain taaki cleaned movie text ko meaningful numerical vectors me convert kar sakein.  
`max_features=50000` important words limit karta hai, `ngram_range=(1,2)` single aur two-word phrases capture karta hai, aur `stop_words='english'` common words remove karta hai.

In [ ]:
tfidf_matrix = tfidf.fit_transform(df['tags'])

In [ ]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1548291 stored elements and shape (45447, 50000)>

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity


## Cosine Similarity (Intuition + Math)

Cosine similarity do vectors ke **angle** ko measure karta hai.  
Angle jitna **chhota**, similarity utni **zyada**.

\[
\text{Cosine Similarity} = \frac{A \cdot B}{||A|| \, ||B||}
\]

- **cos(0°) = 1 → perfectly similar**
- **cos(45°) ≈ 0.71 → moderately similar**
- **cos(90°) = 0 → completely different**

---

## Example (Movie Text)

### Case 1
**S1:** `virat kohli`  
**S2:** `virat`  

Common word: `virat`

Angle ≈ **45°**


Similarity ≈ **cos(45°) = 0.71**

➡ Meaning: **partially similar**

---

### Case 2
**S1:** `virat`  
**S2:** `kohli`

Common words: **none**

Angle ≈ **90°**


Similarity = **cos(90°) = 0**

➡ Meaning: **not similar**

---

### Case 3
**S1:** `virat kohli`  
**S2:** `virat kohli`

Angle = **0°**


Similarity = **cos(0°) = 1**

➡ Meaning: **exactly same**

---

## Why Important in Your Movie Recommender

TF-IDF movie text ko **vectors** banata hai, aur **cosine similarity** un vectors ke angle compare karke **similar movies recommend karta hai**.

In [ ]:
def recommend(title, n = 10):
  if title not in indices:
    return ['Movie not found']

  idx = indices[title]
  sim_score = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()# flatten sesab 1d bangea
  similar_idx = sim_score.argsort()[::-1][1:n+1]
  #argsort se index basis pe sort hua and index ke basis pe top 10 similar ko choose kiya
  return df['title'].iloc[similar_idx]

### Why We Used a Graph

Graph sirf intuition samjhane ke liye use kiya gaya tha kyuki example sentences chhote the.  
Real NLP me sentences bahut bade hote hain, isliye similarity calculate karne ke liye **cosine similarity ka mathematical formula** use kiya jata hai.

### Cosine Similarity Formula

\[
\text{Cosine Similarity} =
\frac{\sum_{i=1}^{n} A_i B_i}
{\sqrt{\sum_{i=1}^{n} A_i^2} \times \sqrt{\sum_{i=1}^{n} B_i^2}}
\]

**Variables:**

- \(A_i\) → vector A ka ith element (sentence 1)  
- \(B_i\) → vector B ka ith element (sentence 2)  
- \(n\) → total features / words  

### Example

S1: **virat kohli**  
S2: **virat**

Vectors (simple example):


Angle ≈ **45°**

\[
cos(45^\circ) \approx 0.71
\]

➡ Matlab sentences **partially similar** hain kyuki dono me **“virat”** common hai.

In [ ]:
recommend('Avatar',5)

26549                                      Avatar 2
26555                                Thor: Ragnarok
13883                          The Inhabited Island
43437                        Moontrap: Target Earth
6414     Lara Croft Tomb Raider: The Cradle of Life
Name: title, dtype: object

In [ ]:
import pickle

pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl','wb'))

pickle.dump(indices,open('indices.pkl','wb'))

df.to_pickle('df.pkl')

pickle.dump(tfidf,open('tfidf.pkl','wb'))